### ISSUE TITLE
ModuleNotFoundError: No module named 'datatree'

### ISSUE THREAD

**Issue by Jonathan-Holmes-Bioinformatics** [saeyslab/napari-sparrow#210]
Hi,

I am trying to install Sparrow onto the following system:
`5.15.146.1-microsoft-standard-WSL2`
`"Ubuntu 22.04.3 LTS"`
`conda 23.7.4`

Following creation of the napari-sparrow conda environment through the provided yml file and pip install of git+https://github.com/saeyslab/napari-sparrow.git. The following error appears when importing sparrow in python:

```
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sparrow
/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/dask/dataframe/__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/__init__.py", line 9, in <module>
    from . import (  # noqa: E402
  File "/home/biol0216/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/datasets/__init__.py", line 1, in <module>
    from .cluster_blobs import cluster_blobs, multisample_blobs
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/datasets/cluster_blobs.py", line 16, in <module>
    from sparrow.table import add_regionprop_features
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/table/__init__.py", line 1, in <module>
    from ._allocation import allocate, bin_counts
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/table/_allocation.py", line 20, in <module>
    from sparrow.image._image import _get_spatial_element, _get_translation
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/image/__init__.py", line 1, in <module>
    from sparrow.utils.pylogger import get_pylogger
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/utils/__init__.py", line 1, in <module>
    from sparrow.utils._query import bounding_box_query
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/utils/_query.py", line 10, in <module>
    from sparrow.image._image import _get_spatial_element, add_labels_layer
  File "/home/anaconda3/envs/napari-sparrow/lib/python3.10/site-packages/sparrow/image/_image.py", line 9, in <module>
    from datatree import DataTree
ModuleNotFoundError: No module named 'datatree'
```

Installing xarray-datatree produces a conflict error:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
multiscale-spatial-image 2.0.2 requires xarray>=2024.10.0, but you have xarray 2024.7.0 which is incompatible.
spatialdata 0.2.6 requires xarray>=2024.10.0, but you have xarray 2024.7.0 which is incompatible.`

Do you know if there is a workaround for this, have i made an error during the installation or is Sparrow not compatible with WSL? I have tried initializing the conda environment from Harpy as suggested in another issue (#208) but receive a similar error. 

Thank you

**Comment by ArneDefauw** [comment]
Building the conda environment using this yml https://github.com/saeyslab/harpy/blob/main/environment.yml should work on wsl.

Then I suggest you use the compatible library harpy, thus in an active conda environment:

pip install git+https://github.com/saeyslab/harpy.git


API of harpy is same as sparrow, as is functionality for transcriptomics. Just change` import sparrow `with` import harpy`


If you still have problems, do not hesistate to reach out!
